import { pitchCard, rankSignals } from './core.js';
const signals=[
{id:1,theme:'Heat safety at bus stops',type:'Reader questions',count:14,sourceTypes:3,civicValue:5,urgency:5,sensitive:false,summary:'Readers are asking where shaded stops, water access, and heat alerts are available during the afternoon commute.'},
{id:2,theme:'New property-tax notices',type:'Search',count:19,sourceTypes:2,civicValue:5,urgency:4,sensitive:false,summary:'Search and help-desk patterns suggest homeowners need a clear explainer before payment deadlines.'},
{id:3,theme:'Rumor about school closure',type:'Comments',count:9,sourceTypes:1,civicValue:4,urgency:5,sensitive:true,summary:'A concentrated comment thread references an unverified closure claim; corroborate independently before coverage.'},
{id:4,theme:'Accessible voting locations',type:'Public agenda',count:7,sourceTypes:4,civicValue:5,urgency:3,sensitive:false,summary:'Upcoming agenda changes and reader questions point to a service explainer opportunity.'}
];
let active=1; const $=s=>document.querySelector(s);
function render(){const filters={type:$('#type').value,minimumEvidence:Number($('#evidence').value)};const ranked=rankSignals(signals,filters);if(!ranked.some(s=>s.id===active))active=ranked[0]?.id;$('#queue').innerHTML=ranked.length?ranked.map(s=>`<button class="signal ${s.id===active?'active':''}" data-id="${s.id}"><span class="tag">${s.type}</span><h3>${s.theme}</h3><p>${s.count} sources · ${s.evidence} evidence</p><b>${s.score}</b></button>`).join(''):'<p>No signals meet this review threshold.</p>';document.querySelectorAll('.signal').forEach(x=>x.onclick=()=>{active=Number(x.dataset.id);render()});const selected=signals.find(s=>s.id===active);if(!selected){$('#detail').innerHTML='';return}const pitch=pitchCard(selected);$('#detail').innerHTML=`<p class="eyebrow">REVIEWABLE PITCH</p><span class="status ${selected.sensitive?'warning':''}">${selected.sensitive?'MANUAL REVIEW':'READY FOR EDITOR REVIEW'}</span><h2>${pitch.question}</h2><h3>Suggested framing</h3><p>${pitch.framing}</p><div class="sourcebox"><strong>Evidence trail</strong><p>${pitch.sources}</p><p>${pitch.caveat}</p></div><label>Editor disposition<select id="disposition"><option>Monitor</option><option>Investigate</option><option>Dismiss as unsupported</option></select></label><button id="save">Save review note</button><p id="confirmation" aria-live="polite"></p>`;$('#save').onclick=()=>{$('#confirmation').textContent=`Saved as “${$('#disposition').value}” in this demo.`}};
$('#type').onchange=render;$('#evidence').oninput=()=>{$('#evidence-value').textContent=$('#evidence').value;render()};render();
